// File operation utilities: generated file tracking, analytics, read/edit context
// Sources: generatedFiles.ts, fileOperationAnalytics.ts, readEditContext.ts
module;

#include <chrono>
#include <cstddef>
#include <cstdint>
#include <expected>
#include <filesystem>
#include <mutex>
#include <optional>
#include <string>
#include <string_view>
#include <unordered_map>
#include <unordered_set>
#include <vector>

export module cc.utils.file_operations;

import cc.utils.async;

export namespace cc::utils::file_ops {

// =========================================================================
// GeneratedFileTracker - Track files generated by the tool
// =========================================================================
class GeneratedFileTracker {
public:
    GeneratedFileTracker() = default;

    /// Mark a file as generated
    void track(const std::filesystem::path& file_path);

    /// Remove a file from tracking
    void untrack(const std::filesystem::path& file_path);

    /// Check if a file is tracked as generated
    [[nodiscard]] bool is_generated(const std::filesystem::path& file_path) const;

    /// Get all currently tracked generated files
    [[nodiscard]] std::vector<std::filesystem::path> get_generated_files() const;

    /// Clear all tracking data
    void clear();

private:
    mutable std::mutex mutex_;
    std::unordered_set<std::string> tracked_files_;
};

// =========================================================================
// FileOperation - Record of a single file operation
// =========================================================================
enum class FileOperationType : uint8_t {
    Read,
    Write,
    Create,
    Delete,
    Rename,
    Patch,
};

struct FileOperation {
    FileOperationType type;
    std::filesystem::path path;
    std::chrono::system_clock::time_point timestamp;
    std::optional<std::string> tool_name;
    std::optional<size_t> bytes_affected;
};

// =========================================================================
// FileOperationStats - Aggregated statistics
// =========================================================================
struct FileOperationStats {
    size_t total_operations;
    size_t reads;
    size_t writes;
    size_t creates;
    size_t deletes;
    size_t renames;
    size_t patches;
    size_t total_bytes_read;
    size_t total_bytes_written;
};

// =========================================================================
// FileOperationAnalytics - Record and query file operation history
// =========================================================================
class FileOperationAnalytics {
public:
    FileOperationAnalytics() = default;

    /// Record a file operation
    void record(FileOperation op);

    /// Get aggregated stats
    [[nodiscard]] FileOperationStats get_stats() const;

    /// Get the N most recent operations
    [[nodiscard]] std::vector<FileOperation> get_recent_operations(
        size_t limit
    ) const;

    /// Get operations filtered by type
    [[nodiscard]] std::vector<FileOperation> get_operations_by_type(
        FileOperationType type
    ) const;

    /// Clear all recorded operations
    void clear();

private:
    mutable std::mutex mutex_;
    std::vector<FileOperation> operations_;
};

// =========================================================================
// ReadEditContext - Context information for file read/edit operations
// =========================================================================
struct FileContext {
    std::filesystem::path path;
    std::string content;
    size_t total_lines;
    std::optional<size_t> start_line;     // 1-based, if partial read
    std::optional<size_t> end_line;       // 1-based, if partial read
    std::string language;                 // detected language identifier
};

struct EditContext {
    FileContext file;
    std::string surrounding_content;      // context around edit point
    size_t edit_start_line;               // 1-based
    size_t edit_end_line;                 // 1-based
};

// =========================================================================
// File context reading functions
// =========================================================================

/// Read full context of a single file
[[nodiscard]] async::Task<std::expected<FileContext, std::string>>
read_file_context(
    const std::filesystem::path& path
);

/// Read context of a file with line range
[[nodiscard]] async::Task<std::expected<FileContext, std::string>>
read_file_context(
    const std::filesystem::path& path,
    size_t start_line,
    size_t end_line
);

/// Read context for multiple files
[[nodiscard]] async::Task<std::expected<std::vector<FileContext>, std::string>>
read_multiple_file_context(
    const std::vector<std::filesystem::path>& paths
);

/// Get edit context (file content + surrounding context for an edit region)
[[nodiscard]] async::Task<std::expected<EditContext, std::string>>
get_edit_context(
    const std::filesystem::path& path,
    size_t edit_start_line,
    size_t edit_end_line
);

} // namespace cc::utils::file_ops
